window.MVL_DATA = {
  livestream: {
    // Replace these when the official stream is ready.
    youtubeUrl: 'https://www.youtube.com/',
    youtubeId: '',
  },

  teams: [
    { id: 'metarice-x', name: 'Metarice X', tag: 'Violet Division', grad: ['#7C3BFF', '#2E00A8'], pos: '76% 24%' },
    { id: 'metarice-y', name: 'Metarice Y', tag: 'Green Division', grad: ['#00B453', '#067B45'], pos: '76% 20%' },
    { id: 'thurstrap', name: 'Thurstrap', tag: 'Aqua Division', grad: ['#10E0D4', '#078D96'], pos: '72% 22%' },
    { id: 'gizmo', name: 'Gizmo', tag: 'Pink Division', grad: ['#FF3FB4', '#D50083'], pos: '78% 25%' },
    { id: 'gremlins', name: 'Gremlins', tag: 'Red Division', grad: ['#F51642', '#B90025'], pos: '20% 72%' },
    { id: 'ssvc', name: 'SSVC', tag: 'Yellow Division', grad: ['#FFE44D', '#D6A900'], pos: '20% 74%' },
    { id: 's24', name: 'S24', tag: 'Blue Division', grad: ['#3478FF', '#0039B8'], pos: '78% 24%' },
    { id: 'up-leftout', name: 'UP Leftout', tag: 'Orange Division', grad: ['#FF9A05', '#FF5A00'], pos: '22% 72%' },
  ],

  sponsors: [
    { name: 'Converge', tier: 'Official Partner', order: 1, logo: 'assets/Sponsor Logos/Official Partners/Converge.png' },
    { name: 'Immuni', tier: 'Official Partner', order: 2, logo: 'assets/Sponsor Logos/Official Partners/Immuni - Company 1.png' },
    { name: 'JBL', tier: 'Official Partner', order: 3, logo: 'assets/Sponsor Logos/Official Partners/JBL.png' },
    { name: 'KG Body Recovery', tier: 'Official Partner', order: 4, logo: 'assets/Sponsor Logos/Official Partners/KG Body Recovery.png' },
    { name: 'Lysol', tier: 'Official Partner', order: 5, logo: 'assets/Sponsor Logos/Official Partners/Lysol Logo-01.png' },

    { name: 'Aveeno', tier: 'Co-presenter', order: 1, logo: 'assets/Sponsor Logos/Co-Presenters/Aveeno.png' },
    { name: 'Camou', tier: 'Co-presenter', order: 2, logo: 'assets/Sponsor Logos/Co-Presenters/Camou.png' },
    { name: 'DoubleDragon Corporation', tier: 'Co-presenter', order: 3, logo: 'assets/Sponsor Logos/Co-Presenters/DoubleDragon Corporation logo final (3).png' },
    { name: 'Dr. O White', tier: 'Co-presenter', order: 4, logo: 'assets/Sponsor Logos/Co-Presenters/Dr O White Logo.png' },
    { name: 'Future Glow', tier: 'Co-presenter', order: 5, logo: 'assets/Sponsor Logos/Co-Presenters/future glow.png' },
    { name: 'Listerine', tier: 'Co-presenter', order: 6, logo: 'assets/Sponsor Logos/Co-Presenters/Listerine.png' },
    { name: 'OFBANK', tier: 'Co-presenter', order: 7, logo: 'assets/Sponsor Logos/Co-Presenters/OFBANK LOGO.jpg' },
    { name: 'Oxecure', tier: 'Co-presenter', order: 8, logo: 'assets/Sponsor Logos/Co-Presenters/Oxecure.png' },
    { name: 'Tropicana', tier: 'Co-presenter', order: 9, logo: 'assets/Sponsor Logos/Co-Presenters/tropicana.png' },
    { name: 'Vitanature', tier: 'Co-presenter', order: 10, logo: 'assets/Sponsor Logos/Co-Presenters/VITANATURE White Logo.png' },

    { name: 'BPI Trade', tier: 'Major Sponsor', order: 1, logo: 'assets/Sponsor Logos/Major Sponsors/bpi trade horizontal.png' },
    { name: 'F2 Logistics', tier: 'Major Sponsor', order: 2, logo: 'assets/Sponsor Logos/Major Sponsors/F2 Logistics.png' },
    { name: 'Old Spice', tier: 'Major Sponsor', order: 3, logo: 'assets/Sponsor Logos/Major Sponsors/Old Spice.png' },
    { name: 'PGA Cars', tier: 'Major Sponsor', order: 4, logo: 'assets/Sponsor Logos/Major Sponsors/PGA Cars Logo.jpg' },
    { name: 'Western Appliances', tier: 'Major Sponsor', order: 5, logo: 'assets/Sponsor Logos/Major Sponsors/Western Appliances.png' },

    { name: 'Nature\'s Spring', tier: 'Minor Sponsor', order: 1, logo: 'assets/Sponsor Logos/Minor Sponsors/Natures Spring-Logo-TransparentBG-(Low Resolution).png' },
    { name: 'Potato Corner', tier: 'Minor Sponsor', order: 2, logo: 'assets/Sponsor Logos/Minor Sponsors/Potato Corner PPS Logo.png' },
  ],

  games: [
    {
      id: 'g1',
      day: 1,
      court: 'Gameville Ball Park',
      startsAt: '2026-08-29T21:00:00+08:00',
      teamA: 'metarice-x',
      teamB: 'metarice-y',
      status: 'final',
      winner: 'metarice-y',
      sets: [
        { a: 25, b: 21 },
        { a: 24, b: 26 },
        { a: 10, b: 15 },
      ],
      playerOfGame: { name: 'TBD', team: 'metarice-y' },
      youtubeId: '',
      duration: '1:42:10',
    },
    {
      id: 'g2',
      day: 1,
      court: 'Gameville Ball Park',
      startsAt: '2026-08-29T22:00:00+08:00',
      teamA: 'thurstrap',
      teamB: 'gizmo',
      status: 'final',
      winner: 'gizmo',
      sets: [
        { a: 25, b: 21 },
        { a: 24, b: 26 },
        { a: 10, b: 15 },
      ],
      playerOfGame: { name: 'TBD', team: 'gizmo' },
      youtubeId: '',
      duration: '1:28:44',
    },
    {
      id: 'g3',
      day: 1,
      court: 'Gameville Ball Park',
      startsAt: '2026-08-29T23:00:00+08:00',
      teamA: 'gremlins',
      teamB: 'ssvc',
      status: 'final',
      winner: 'ssvc',
      sets: [
        { a: 25, b: 21 },
        { a: 24, b: 26 },
        { a: 10, b: 15 },
      ],
      playerOfGame: { name: 'TBD', team: 'ssvc' },
      youtubeId: '',
      duration: '1:51:02',
    },
    {
      id: 'g4',
      day: 2,
      court: 'Gameville Ball Park',
      startsAt: '2026-08-30T21:00:00+08:00',
      teamA: 's24',
      teamB: 'up-leftout',
      status: 'pending',
      winner: null,
      sets: [],
      playerOfGame: null,
      youtubeId: '',
      duration: '',
    },
    {
      id: 'g5',
      day: 2,
      court: 'Gameville Ball Park',
      startsAt: '2026-08-30T22:00:00+08:00',
      teamA: 'metarice-x',
      teamB: 'thurstrap',
      status: 'pending',
      winner: null,
      sets: [],
      playerOfGame: null,
      youtubeId: '',
      duration: '',
    },
    {
      id: 'g6',
      day: 3,
      court: 'Gameville Ball Park',
      startsAt: '2026-08-31T21:00:00+08:00',
      teamA: 'metarice-y',
      teamB: 'gremlins',
      status: 'pending',
      winner: null,
      sets: [],
      playerOfGame: null,
      youtubeId: '',
      duration: '',
    },
    {
      id: 'g7',
      day: 4,
      court: 'Gameville Ball Park',
      startsAt: '2026-09-05T21:00:00+08:00',
      teamA: 'gizmo',
      teamB: 's24',
      status: 'pending',
      winner: null,
      sets: [],
      playerOfGame: null,
      youtubeId: '',
      duration: '',
    },
    {
      id: 'g8',
      day: 5,
      court: 'Gameville Ball Park',
      startsAt: '2026-09-06T21:00:00+08:00',
      teamA: 'ssvc',
      teamB: 'up-leftout',
      status: 'pending',
      winner: null,
      sets: [],
      playerOfGame: null,
      youtubeId: '',
      duration: '',
    },
  ],
};
