window.MVL_DATA = {
  livestream: {
    // Replace these when the official stream is ready.
    youtubeUrl: 'https://www.youtube.com/',
    youtubeId: '',
  },

  teams: [
    { id: 'dvo', name: 'DVO', tag: 'Green Division', grad: ['#00B453', '#067B45'], pos: '76% 20%' },
    { id: 'giggles', name: 'Giggles', tag: 'Aqua Division', grad: ['#10E0D4', '#078D96'], pos: '72% 22%' },
    { id: 'thurstrap', name: 'Thurstrap', tag: 'Orange Division', grad: ['#FF9A05', '#FF5A00'], pos: '22% 72%' },
    { id: 'metarice-blue', name: 'Metarice', tag: 'Blue Division', grad: ['#3478FF', '#0039B8'], pos: '78% 24%' },
    { id: 'princess', name: 'Princess', tag: 'Red Division', grad: ['#F51642', '#B90025'], pos: '20% 72%' },
    { id: 'metarice-violet', name: 'Metarice', tag: 'Violet Division', grad: ['#7C3BFF', '#2E00A8'], pos: '76% 24%' },
    { id: 's24', name: 'S24', tag: 'Yellow Division', grad: ['#FFE44D', '#D6A900'], pos: '20% 74%' },
    { id: 'up', name: 'UP', tag: 'Pink Division', grad: ['#FF3FB4', '#D50083'], pos: '78% 25%' },
  ],

  sponsors: [
    'ATOMM STUDIOS', 'AVEENO', 'CAMOU', 'CONVERGE',
    'DUREX', 'GAMEVILLE BALL PARK', 'GAVISCON', 'KG BODY RECOVERY',
  ],

  games: [
    {
      id: 'g1',
      day: 1,
      court: 'Gameville Ball Park',
      startsAt: '2026-08-15T21:00:00+08:00',
      teamA: 'dvo',
      teamB: 'giggles',
      status: 'final',
      winner: 'giggles',
      sets: [
        { a: 25, b: 21 },
        { a: 24, b: 26 },
        { a: 10, b: 15 },
      ],
      playerOfGame: { name: 'TBD', team: 'giggles' },
      youtubeId: '',
      duration: '1:42:10',
    },
    {
      id: 'g2',
      day: 1,
      court: 'Gameville Ball Park',
      startsAt: '2026-08-15T22:00:00+08:00',
      teamA: 'thurstrap',
      teamB: 'metarice-blue',
      status: 'final',
      winner: 'metarice-blue',
      sets: [
        { a: 25, b: 21 },
        { a: 24, b: 26 },
        { a: 10, b: 15 },
      ],
      playerOfGame: { name: 'TBD', team: 'metarice-blue' },
      youtubeId: '',
      duration: '1:28:44',
    },
    {
      id: 'g3',
      day: 1,
      court: 'Double Play',
      startsAt: '2026-08-15T23:00:00+08:00',
      teamA: 'princess',
      teamB: 'metarice-violet',
      status: 'final',
      winner: 'metarice-violet',
      sets: [
        { a: 25, b: 21 },
        { a: 24, b: 26 },
        { a: 10, b: 15 },
      ],
      playerOfGame: { name: 'TBD', team: 'metarice-violet' },
      youtubeId: '',
      duration: '1:51:02',
    },
    {
      id: 'g4',
      day: 2,
      court: 'Gameville Ball Park',
      startsAt: '2026-08-16T21:00:00+08:00',
      teamA: 's24',
      teamB: 'up',
      status: 'pending',
      winner: null,
      sets: [],
      playerOfGame: null,
      youtubeId: '',
      duration: '',
    },
    {
      id: 'g5',
      day: 2,
      court: 'Double Play',
      startsAt: '2026-08-16T22:00:00+08:00',
      teamA: 'dvo',
      teamB: 'thurstrap',
      status: 'pending',
      winner: null,
      sets: [],
      playerOfGame: null,
      youtubeId: '',
      duration: '',
    },
    {
      id: 'g6',
      day: 3,
      court: 'Gameville Ball Park',
      startsAt: '2026-08-21T21:00:00+08:00',
      teamA: 'giggles',
      teamB: 'princess',
      status: 'pending',
      winner: null,
      sets: [],
      playerOfGame: null,
      youtubeId: '',
      duration: '',
    },
    {
      id: 'g7',
      day: 4,
      court: 'Gameville Ball Park',
      startsAt: '2026-08-22T21:00:00+08:00',
      teamA: 'metarice-blue',
      teamB: 's24',
      status: 'pending',
      winner: null,
      sets: [],
      playerOfGame: null,
      youtubeId: '',
      duration: '',
    },
    {
      id: 'g8',
      day: 5,
      court: 'Double Play',
      startsAt: '2026-08-23T21:00:00+08:00',
      teamA: 'metarice-violet',
      teamB: 'up',
      status: 'pending',
      winner: null,
      sets: [],
      playerOfGame: null,
      youtubeId: '',
      duration: '',
    },
  ],
};
